### ISSUE TITLE
the oxidation states dataset is outdated. Can you guys update it according to wikipedia?

### ISSUE THREAD

**Issue by usccolumbia** [WMD-group/SMACT#32] opened 2020-09-06 08:16 UTC
https://github.com/WMD-group/SMACT/blob/master/smact/data/oxidation_states.txt
some of the data maybe even wrong, such as Ir element's oxidation states.

https://en.wikipedia.org/wiki/Oxidation_state#cite_note-99

**Comment by keeeto** [comment] 2020-09-12 16:23
Is Ir the only specific example that you have in mind here @usccolumbia? In that case the issue is being addressed in PR #33. If there are any other specific examples we would apprciate the input. Thanks.

**Comment by usccolumbia** [comment] 2020-09-12 18:55
> Is Ir the only specific example that you have in mind here @usccolumbia? In that case the issue is being addressed in PR #33. If there are any other specific examples we would apprciate the input. Thanks.

There are quite a few others that are not consisent with the wikipedia tables ,which seems to be more updated.  I suggest you guys check against that table to update your oudated ones.  The oxidation states affect many materials screening function downstream......

**Comment by keeeto** [comment] 2020-09-12 20:33
Okay this is probably going to require a bit more discussion than a quick fix. I am not sure if we are using wikipedia as our cannonical source for oxidation states. Thanks for raising the point, it's probably something we will think about before a next big version change. I'm happy to make quick fixes for obvious errors such as the Ir case, but this feels like it could be a bigger question.

**Comment by ajjackson** [comment] 2020-09-13 08:59
> I am not sure if we are using wikipedia as our cannonical source for oxidation states. 

If it helps, I _am_ sure that we are _not_ using it as a canonical source. But it can be useful as a prompt to consider certain states - and perhaps we would reach the same conclusions.

**Comment by keeeto** [comment] 2020-09-19 14:32
So basically yeah. We are open to keeping an eye on new oxidation states. But there are no plans to make wikipedia our source of oxidation state information.

**Closed by keeeto** 2020-09-19 14:32 UTC
